import json
from pathlib import Path
P=Path(r'D:\Video Projects\NPC Package\Characters\Elliot\V3');ROOT=P.parents[2]
for file in [ROOT/'Characters/Elliot/README.md',P/'README.md']:
    t=file.read_text(encoding='utf-8-sig').replace('12 simple facial controls','21 facial controls').replace('12 facial controls','21 facial controls')
    t=t.replace('All 121 audio files are unchanged and unconnected.','All 121 audio files are unchanged. The first recording is connected to the isolated talking demo in `V3/Performance`; autonomous gameplay speech remains pending.')
    t=t.replace('All 121 voice/audio files are preserved. No voice playback or lip-sync integration was added.','All 121 original voice/audio files are preserved. `Performance/Previews/Elliot_First_Talking_Shot.mp4` is the first audio-driven performance. See `Performance/README.md` for reusable controls, scope and verification.')
    t=t.replace('This is the first candidate in a new art direction. Structural or gameplay checks do not establish artistic approval or complete animation polish.','Alfie approved this exact appearance on 30 September 2026. Proportions, clothing and style are locked. Performance controls were added without changing base geometry. Structural or gameplay checks do not establish complete animation polish.')
    t=t.replace('`scripts/build_game_elliot.py`: reproducible build through Blender Python','`scripts/build_game_elliot.py`: historical geometry build through Blender Python (do not rerun over the approved performance master)')
    file.write_text(t,encoding='utf-8')
manifest=json.loads((P/'animation_manifest.json').read_text());manifest['voice_integration']={'scope':'isolated talking demo','recordings_connected':1,'autonomous_game_events':False};(P/'animation_manifest.json').write_text(json.dumps(manifest,indent=2))
file=P/'scripts/validate_game_elliot.py';t=file.read_text().replace(')==12',')==21').replace("'facial_controls':12","'facial_controls':21").replace("'voice_integration':False","'voice_integration':'one isolated talking demo'");file.write_text(t)
(P/'Performance/Play_Talking_Elliot.cmd').write_text('@echo off\n"C:\\Users\\Alfie\\Downloads\\Godot_v4.7.1-stable_win64.exe\\Godot_v4.7.1-stable_win64_console.exe" --path "D:\\Video Projects\\NPC Package\\GodotTest" --script res://tests/talking_elliot_demo.gd\n')
(P/'Performance/cues/CLOSE_01.performance.json').write_text(json.dumps({'id':'CLOSE_01','audio':'../../Voice/Bit close, mate.mp3','mouth_timing':'CLOSE_01.rhubarb.json','expression':'uncomfortable','body':[{'time':0,'clip':'HAND_UP_BOUNDARY'},{'time':1.25,'clip':'STEP_BACK_SMALL'},{'time':2.25,'clip':'IDLE_NERVOUS_A'}],'retreat_m':.16,'eyes':'glance away and down','appearance_locked':True},indent=2))
with (P/'VALIDATION.md').open('a',encoding='utf-8') as f:f.write('\n\n## Approved appearance and talking milestone\n\nThe appearance is now user-approved and locked. Facial controls increased from 12 to 21 without changing resting geometry. The first original Gama recording is connected in the isolated talking demo. See Performance/media_validation.json and performance_validation.json. All 121 audio hashes match, live/offline speech checks pass, and all 11 presence scenarios pass. Phone diagnostic rendering revealed an unfinished ear-contact pose; it is not a completed phone performance. Unreal runtime and independent listening remain untested.\n')
print('PERFORMANCE_PACKAGE_UPDATED')
